authors:
  <qihang>:
    name: Qihang     # Author name
    description: Learning By Doing # Author description
    avatar: https://avatars.githubusercontent.com/u/148497514?v=4         # Author avatar