# .github/workflows/receive-update.yml
name: update_content

on:
  # monitor the event from the central repo
  repository_dispatch:
    types: [update_repo]
  # can be triggered manually
  workflow_dispatch:

# set the default permissions for the workflow
permissions:
  contents: write # need write permission to commit and push changes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout the edge repo, which is the repo we will modify
      - name: Checkout Edge Repo (self)
        uses: actions/checkout@v4

      # step 2: checkout the central repo
      - name: Checkout Central Logic Repo
        uses: actions/checkout@v4
        with:
          repository: 'Qihang-Zhang/Polyrhythm' # your central repo name
          ref: 'main' # suggest to point to a stable tag, like v1.0.0, to avoid being affected by the main branch development
          token: ${{ secrets.POLYRHYTHM_READ_TOKEN }} # need a PAT to read the central private repo
          path: './central-logic' # download the central repo logic to this subdirectory

      # step 3: run the sync script, and pass the payload parameters through env
      - name: Run Sync Script
        env:
          # read the parameters from the payload of the dispatch event, and set them as environment variables
          SYNC_SOURCE_REPO: ${{ github.event.client_payload.source_repo }}
          SYNC_SOURCE_REF: ${{ github.event.client_payload.source_ref }}
          SYNC_SOURCE_DIR: ${{ github.event.client_payload.source_dir }}
          SYNC_TARGET_DIR: ${{ github.event.client_payload.target_dir }}
          # pass the token to read the central repo
          CORE_REPO_TOKEN: ${{ secrets.POLYRHYTHM_READ_TOKEN }}
        run: |
          bash ./central-logic/scripts/sync-files.sh

      - name: Clean up temporary logic directory
        if: always() 
        run: rm -rf ./central-logic
